services:
  - type: web
    name: repofit-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: repofit-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: repofit-backend
          envVarKey: RENDER_EXTERNAL_URL
