import React, { useState } from 'react';

const DashboardView = ({ data, onBack, onNewJD }) => {
  const [drawerOpen, setDrawerOpen] = useState(false);

  if (!data) return null;
  const { job_profile, top_matches } = data;
  const bestMatch = top_matches && top_matches.length > 0 ? top_matches[0] : null;

  const scoreColor = (score) => {
    if (score >= 80) return '#22c55e';
    if (score >= 60) return '#eab308';
    return '#ef4444';
  };

  const handleDownload = () => {
    const lines = [];
    lines.push('=== RepoFit Analysis Report ===');
    lines.push(`Role: ${job_profile.role_title}`);
    lines.push('');
    lines.push('--- Required Skills ---');
    lines.push(job_profile.required_skills.join(', ') || 'None detected');
    lines.push('');
    lines.push('--- Preferred Skills ---');
    lines.push(job_profile.preferred_skills.join(', ') || 'None detected');
    lines.push('');
    lines.push('--- Repository Matches ---');
    top_matches.forEach((m, i) => {
      lines.push('');
      lines.push(`[${i + 1}] ${m.repo_name} — ${m.score}%`);
      lines.push(`    Type: ${m.project_type}`);
      lines.push(`    Why: ${m.why_it_matches}`);
      if (m.matching_skills?.length) lines.push(`    Matching: ${m.matching_skills.join(', ')}`);
      if (m.missing_skills?.length) lines.push(`    Missing: ${m.missing_skills.join(', ')}`);
      if (m.resume_bullets?.length) {
        lines.push('    Resume Bullets:');
        m.resume_bullets.forEach(b => lines.push(`      - ${b}`));
      }
    });
    lines.push('');
    lines.push('Generated by RepoFit AI — Code analyzed, never stored.');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `repofit-report-${job_profile.role_title.replace(/\s+/g, '_').toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&family=Space+Mono:wght@400;700&display=swap');

        * { box-sizing: border-box; }
        body { background: #050505; margin: 0; }

        @keyframes blink {
          0%, 100% { opacity: 1; } 50% { opacity: 0; }
        }
        @keyframes flicker {
          0%, 100% { opacity: 1; }
          92% { opacity: 1; } 93% { opacity: 0.8; }
          94% { opacity: 1; } 95% { opacity: 0.9; }
        }
        @keyframes pulse-score {
          0%, 100% { filter: drop-shadow(0 0 4px rgba(34,197,94,0.4)); }
          50% { filter: drop-shadow(0 0 12px rgba(34,197,94,0.8)); }
        }
        @keyframes scanIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes drawerSlide {
          from { transform: translateX(100%); }
          to { transform: translateX(0); }
        }

        .db-root {
          font-family: 'JetBrains Mono', 'Fira Code', monospace;
          background: #050505;
          min-height: 100vh;
          color: #e2e8e2;
        }

        .db-root::before {
          content: '';
          position: fixed; top: 0; left: 0; right: 0; bottom: 0;
          background: repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.03) 2px, rgba(0,0,0,0.03) 4px);
          pointer-events: none; z-index: 9999;
          animation: flicker 8s infinite;
        }

        .db-nav {
          position: sticky; top: 0; z-index: 200;
          background: rgba(5,5,5,0.96);
          border-bottom: 1px solid #1a2a1a;
          backdrop-filter: blur(8px);
        }

        .db-nav-inner {
          display: flex; justify-content: space-between; align-items: center;
          padding: 14px 32px;
          max-width: 1440px; margin: 0 auto;
          gap: 12px;
        }

        .db-logo {
          font-family: 'Space Mono', monospace;
          font-size: 17px; font-weight: 700;
          color: #22c55e;
          text-shadow: 0 0 20px rgba(34,197,94,0.5);
          letter-spacing: -0.5px;
          cursor: pointer;
          transition: text-shadow 0.2s;
        }

        .db-logo:hover { text-shadow: 0 0 32px rgba(34,197,94,0.8); }
        .db-logo span { color: #333; }

        .db-nav-actions {
          display: flex; align-items: center; gap: 8px;
        }

        .db-btn-secondary {
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          color: #3a5a3a;
          background: transparent;
          border: 1px solid #1a2a1a;
          border-radius: 3px;
          padding: 6px 14px;
          cursor: pointer;
          letter-spacing: 0.5px;
          transition: all 0.2s;
          display: flex; align-items: center; gap: 6px;
          white-space: nowrap;
        }

        .db-btn-secondary:hover {
          color: #22c55e;
          border-color: #2a4a2a;
          background: rgba(34,197,94,0.04);
        }

        .db-btn-primary {
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          color: #050505;
          background: #22c55e;
          border: none;
          border-radius: 3px;
          padding: 7px 14px;
          cursor: pointer;
          letter-spacing: 0.5px;
          font-weight: 700;
          transition: all 0.2s;
          display: flex; align-items: center; gap: 6px;
          white-space: nowrap;
        }

        .db-btn-primary:hover {
          background: #16a34a;
          box-shadow: 0 0 16px rgba(34,197,94,0.3);
        }

        /* Mobile drawer toggle */
        .db-drawer-toggle {
          display: none;
          font-family: 'JetBrains Mono', monospace;
          font-size: 11px;
          color: #3a5a3a;
          background: transparent;
          border: 1px solid #1a2a1a;
          border-radius: 3px;
          padding: 6px 12px;
          cursor: pointer;
          gap: 5px;
          align-items: center;
          transition: all 0.2s;
        }

        @media (max-width: 900px) {
          .db-drawer-toggle { display: flex; }
        }

        .db-layout {
          display: flex; flex-direction: row;
          max-width: 1440px; margin: 0 auto;
          position: relative;
        }

        .db-main { flex: 1; padding: 40px 40px 80px 40px; min-width: 0; }

        @media (max-width: 600px) { .db-main { padding: 24px 16px 80px; } }

        /* Header */
        .db-page-header {
          margin-bottom: 36px;
          animation: scanIn 0.4s ease;
        }

        .db-breadcrumb {
          font-size: 10px; color: #2a4a2a;
          letter-spacing: 1px; margin-bottom: 10px;
        }

        .db-page-title {
          font-family: 'Space Mono', monospace;
          font-size: clamp(20px, 3vw, 30px);
          font-weight: 700;
          color: #f0f4f0;
          margin: 0 0 4px 0;
          letter-spacing: -1px;
        }

        .db-page-sub {
          font-size: 11px; color: #2d4a2d;
        }

        /* Summary grid */
        .db-summary {
          display: grid;
          grid-template-columns: 180px 1fr;
          gap: 16px;
          margin-bottom: 40px;
          animation: scanIn 0.5s ease 0.1s both;
        }

        @media (max-width: 640px) { .db-summary { grid-template-columns: 1fr; } }

        .db-card {
          background: #0a0a0a;
          border: 1px solid #1a2a1a;
          border-radius: 6px;
          padding: 24px;
        }

        .db-card-label {
          font-size: 9px;
          text-transform: uppercase;
          letter-spacing: 2px;
          color: #2a4a2a;
          margin-bottom: 16px;
        }

        /* Score ring */
        .db-score-wrap {
          display: flex; flex-direction: column;
          align-items: center;
          gap: 12px;
        }

        .db-score-ring {
          position: relative;
          width: 88px; height: 88px;
          animation: pulse-score 3s ease-in-out infinite;
        }

        .db-score-val {
          position: absolute; inset: 0;
          display: flex; align-items: center; justify-content: center;
          font-family: 'Space Mono', monospace;
          font-size: 20px; font-weight: 700;
          color: #22c55e;
        }

        .db-score-name {
          font-size: 10px; color: #3a5a3a;
          text-align: center; word-break: break-all;
          max-width: 140px;
        }

        /* Skills */
        .db-skills-card {}
        .db-skill-section { margin-bottom: 16px; }
        .db-skill-section:last-child { margin-bottom: 0; }

        .db-skill-section-label {
          font-size: 9px;
          text-transform: uppercase;
          letter-spacing: 2px;
          color: #2a4a2a;
          margin-bottom: 10px;
          display: flex; align-items: center; gap: 6px;
        }

        .db-skill-section-label::before { content: '//'; color: #1a2a1a; }

        .db-skills-row { display: flex; flex-wrap: wrap; gap: 6px; }

        .db-skill-tag {
          font-size: 10px;
          padding: 3px 10px;
          border-radius: 2px;
          border: 1px solid;
          letter-spacing: 0.5px;
          text-transform: uppercase;
          font-family: 'JetBrains Mono', monospace;
        }

        .db-skill-tag.required {
          color: #86efac;
          border-color: #1a3a1a;
          background: rgba(34,197,94,0.04);
        }

        .db-skill-tag.preferred {
          color: #4a6a4a;
          border-color: #1a2a1a;
          background: transparent;
        }

        /* Projects */
        .db-section-header {
          display: flex; align-items: center; gap: 12px;
          margin-bottom: 20px;
          animation: scanIn 0.5s ease 0.2s both;
        }

        .db-section-title {
          font-family: 'Space Mono', monospace;
          font-size: 15px; font-weight: 700;
          color: #86efac;
          margin: 0;
        }

        .db-section-line {
          flex: 1; height: 1px;
          background: linear-gradient(to right, #1a2a1a, transparent);
        }

        .db-projects-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 12px;
        }

        .db-project-card {
          background: #080808;
          border: 1px solid #1a2a1a;
          border-radius: 6px;
          padding: 20px;
          display: flex; flex-direction: column;
          animation: scanIn 0.5s ease both;
          transition: border-color 0.2s;
        }

        .db-project-card:hover { border-color: #2a4a2a; }

        .db-project-card-top {
          display: flex; justify-content: space-between;
          align-items: flex-start; margin-bottom: 10px;
        }

        .db-project-name {
          font-family: 'Space Mono', monospace;
          font-size: 13px; font-weight: 700;
          color: #c4e8c4; word-break: break-all;
          margin: 0 0 3px 0;
        }

        .db-project-type {
          font-size: 9px;
          color: #2a4a2a;
          text-transform: uppercase;
          letter-spacing: 1.5px;
          margin: 0;
        }

        .db-match-badge {
          font-family: 'Space Mono', monospace;
          font-size: 11px; font-weight: 700;
          padding: 3px 8px;
          border-radius: 2px;
          border: 1px solid;
          white-space: nowrap;
          flex-shrink: 0;
          margin-left: 8px;
        }

        .db-project-why {
          font-size: 11px; color: #3a5a3a;
          line-height: 1.8; flex: 1;
          margin-bottom: 12px;
        }

        .db-project-skills-row {
          border-top: 1px solid #111a11;
          padding-top: 12px;
          margin-top: auto;
        }

        .db-project-skills-label {
          font-size: 9px;
          text-transform: uppercase;
          letter-spacing: 1.5px;
          margin-bottom: 6px;
        }

        .db-project-skills-label.missing { color: #7f1d1d; }
        .db-project-skills-label.matching { color: #2a4a2a; }

        .db-project-skills-val {
          font-size: 10px; color: #3a5a3a;
        }

        /* Low match warning */
        .db-low-match-warn {
          margin-top: 10px;
          padding: 6px 10px;
          background: rgba(239,68,68,0.05);
          border: 1px solid #3a1a1a;
          border-radius: 3px;
          font-size: 10px;
          color: #ef4444;
          letter-spacing: 0.5px;
        }

        /* Drawer overlay (mobile) */
        .db-drawer-overlay {
          display: none;
          position: fixed; inset: 0;
          background: rgba(0,0,0,0.6);
          z-index: 150;
        }

        .db-drawer-overlay.open { display: block; }

        /* Sidebar — desktop fixed, mobile drawer */
        .db-sidebar {
          width: 340px;
          flex-shrink: 0;
          background: #070707;
          border-left: 1px solid #1a2a1a;
          padding: 28px 24px;
          display: flex; flex-direction: column;
          min-height: calc(100vh - 53px);
        }

        @media (max-width: 900px) {
          .db-sidebar {
            position: fixed;
            top: 0; right: 0; bottom: 0;
            z-index: 160;
            min-height: 100vh;
            transform: translateX(100%);
            transition: transform 0.3s cubic-bezier(0.4,0,0.2,1);
            overflow-y: auto;
          }
          .db-sidebar.drawer-open {
            transform: translateX(0);
            animation: drawerSlide 0.3s cubic-bezier(0.4,0,0.2,1);
          }
        }

        .db-sidebar-header {
          display: flex; align-items: center;
          justify-content: space-between;
          margin-bottom: 20px;
        }

        .db-sidebar-title {
          font-family: 'Space Mono', monospace;
          font-size: 11px; font-weight: 700;
          color: #3a5a3a; letter-spacing: 1px;
          text-transform: uppercase;
        }

        .db-sidebar-close {
          display: none;
          background: transparent;
          border: none;
          color: #3a5a3a;
          cursor: pointer;
          font-size: 18px;
          line-height: 1;
          padding: 2px;
        }

        @media (max-width: 900px) { .db-sidebar-close { display: block; } }

        /* Resume content in sidebar */
        .db-resume {
          background: #050505;
          border: 1px solid #1a2a1a;
          border-radius: 4px;
          padding: 20px;
          flex: 1;
          overflow-y: auto;
          font-size: 10px;
        }

        .db-resume-head {
          border-bottom: 1px solid #1a2a1a;
          padding-bottom: 14px;
          margin-bottom: 14px;
          text-align: center;
        }

        .db-resume-head-line {
          width: 32px; height: 2px;
          background: #22c55e;
          margin: 0 auto 10px;
        }

        .db-resume-name {
          font-family: 'Space Mono', monospace;
          font-size: 11px; font-weight: 700;
          color: #86efac; text-transform: uppercase;
          letter-spacing: 1px;
        }

        .db-resume-role {
          font-size: 9px; color: #2a4a2a;
          text-transform: uppercase; letter-spacing: 2px;
          margin-top: 3px;
        }

        .db-resume-section-label {
          font-size: 8px; font-weight: 700;
          color: #22c55e;
          text-transform: uppercase; letter-spacing: 2px;
          border-bottom: 1px solid #1a2a1a;
          padding-bottom: 4px; margin-bottom: 12px;
        }

        .db-resume-project { margin-bottom: 14px; }

        .db-resume-proj-name {
          font-size: 10px; font-weight: 700;
          color: #86efac;
          display: flex; justify-content: space-between;
        }

        .db-resume-proj-source { font-size: 8px; color: #2a4a2a; }

        .db-resume-bullets {
          list-style: none; padding: 0; margin: 6px 0 0 0;
        }

        .db-resume-bullets li {
          font-size: 9px; color: #3a5a3a;
          line-height: 1.7;
          padding-left: 12px;
          position: relative;
        }

        .db-resume-bullets li::before {
          content: '›';
          position: absolute; left: 0;
          color: #1a4a1a;
        }

        .db-ats-badge {
          margin-top: 16px;
          background: rgba(34,197,94,0.04);
          border: 1px solid #1a3a1a;
          border-radius: 4px;
          padding: 10px;
          text-align: center;
        }

        .db-ats-badge-title {
          font-size: 9px; font-weight: 700;
          color: #2a5a2a; letter-spacing: 1.5px;
          text-transform: uppercase;
          display: block; margin-bottom: 3px;
        }

        .db-ats-badge-sub {
          font-size: 8px; color: #1a3a1a;
        }
      `}</style>

      <div className="db-root">
        {/* Nav */}
        <header className="db-nav">
          <div className="db-nav-inner">
            <div
              className="db-logo"
              onClick={onBack}
              style={{cursor:'pointer'}}
              role="link"
              tabIndex={0}
              onKeyDown={e => e.key === 'Enter' && onBack?.()}
            >
              Repo<span>/</span>Fit
            </div>

            <div className="db-nav-actions">
              {/* Download report */}
              <button className="db-btn-secondary" onClick={handleDownload}>
                <span className="material-symbols-outlined" style={{fontSize:13}}>download</span>
                download report
              </button>

              {/* New JD button (replaces back arrow) */}
              <button className="db-btn-primary" onClick={onNewJD || onBack}>
                <span className="material-symbols-outlined" style={{fontSize:13, fontVariationSettings:"'FILL' 1"}}>add</span>
                New JD
              </button>

              {/* Mobile drawer toggle */}
              <button className="db-drawer-toggle" onClick={() => setDrawerOpen(true)}>
                <span className="material-symbols-outlined" style={{fontSize:13}}>description</span>
                Resume
              </button>
            </div>
          </div>
        </header>

        {/* Mobile drawer overlay */}
        <div
          className={`db-drawer-overlay${drawerOpen ? ' open' : ''}`}
          onClick={() => setDrawerOpen(false)}
        />

        <div className="db-layout">
          {/* Main */}
          <div className="db-main">
            {/* Header */}
            <div className="db-page-header">
              <div className="db-breadcrumb">analysis / results</div>
              <h2 className="db-page-title">$ {job_profile.role_title}</h2>
              <p className="db-page-sub">// Repository compatibility report</p>
            </div>

            {/* Summary */}
            {bestMatch && (
              <div className="db-summary">
                {/* Score */}
                <div className="db-card" style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                  <div className="db-card-label" style={{textAlign:'center'}}>top match</div>
                  <div className="db-score-wrap">
                    <div className="db-score-ring">
                      <svg viewBox="0 0 88 88" style={{width:'100%',height:'100%',transform:'rotate(-90deg)'}}>
                        <circle cx="44" cy="44" r="36" fill="transparent" stroke="#0f1f0f" strokeWidth="6"/>
                        <circle
                          cx="44" cy="44" r="36" fill="transparent"
                          stroke={scoreColor(bestMatch.score)}
                          strokeDasharray="226.2"
                          strokeDashoffset={226.2 - (226.2 * bestMatch.score) / 100}
                          strokeLinecap="round" strokeWidth="6"
                          style={{transition:'stroke-dashoffset 1s ease'}}
                        />
                      </svg>
                      <div className="db-score-val" style={{color: scoreColor(bestMatch.score)}}>
                        {bestMatch.score}%
                      </div>
                    </div>
                    <div className="db-score-name">{bestMatch.repo_name}</div>
                  </div>
                </div>

                {/* Skills */}
                <div className="db-card db-skills-card">
                  <div className="db-skill-section">
                    <div className="db-skill-section-label">required_skills[]</div>
                    <div className="db-skills-row">
                      {job_profile.required_skills.map((s, i) => (
                        <span key={i} className="db-skill-tag required">{s}</span>
                      ))}
                      {job_profile.required_skills.length === 0 && <span style={{fontSize:10,color:'#2a3a2a'}}>none detected</span>}
                    </div>
                  </div>
                  <div className="db-skill-section" style={{borderTop:'1px solid #0f1a0f',paddingTop:14,marginTop:4}}>
                    <div className="db-skill-section-label">preferred_skills[]</div>
                    <div className="db-skills-row">
                      {job_profile.preferred_skills.map((s, i) => (
                        <span key={i} className="db-skill-tag preferred">{s}</span>
                      ))}
                      {job_profile.preferred_skills.length === 0 && <span style={{fontSize:10,color:'#2a3a2a'}}>none detected</span>}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Projects */}
            <div className="db-section-header">
              <h3 className="db-section-title">project_analysis()</h3>
              <div className="db-section-line"></div>
            </div>

            <div className="db-projects-grid">
              {top_matches.slice(0, 3).map((match, idx) => {
                const sc = scoreColor(match.score);
                const isLow = match.score < 60;
                return (
                  <div
                    key={idx}
                    className="db-project-card"
                    style={{animationDelay:`${idx * 0.08}s`}}
                  >
                    <div className="db-project-card-top">
                      <div>
                        <h4 className="db-project-name">{match.repo_name}</h4>
                        <p className="db-project-type">{match.project_type}</p>
                      </div>
                      <span
                        className="db-match-badge"
                        style={{color: sc, borderColor: sc + '33', background: sc + '08'}}
                      >
                        {match.score}%
                      </span>
                    </div>

                    <p className="db-project-why">{match.why_it_matches}</p>

                    {match.matching_skills?.length > 0 && (
                      <div className="db-project-skills-row">
                        <div className="db-project-skills-label matching">// matching_skills</div>
                        <div className="db-project-skills-val">{match.matching_skills.join(', ')}</div>
                      </div>
                    )}
                    {match.missing_skills?.length > 0 && (
                      <div className="db-project-skills-row">
                        <div className="db-project-skills-label missing">// missing_skills</div>
                        <div className="db-project-skills-val" style={{color:'#5a2a2a'}}>{match.missing_skills.join(', ')}</div>
                      </div>
                    )}

                    {isLow && (
                      <div className="db-low-match-warn">
                        // low match — consider these missing skills first
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Sidebar — resume preview (becomes drawer on mobile) */}
          <aside className={`db-sidebar${drawerOpen ? ' drawer-open' : ''}`}>
            <div className="db-sidebar-header">
              <span className="db-sidebar-title">resume.preview</span>
              <button className="db-sidebar-close" onClick={() => setDrawerOpen(false)}>✕</button>
            </div>

            <div className="db-resume">
              <div className="db-resume-head">
                <div className="db-resume-head-line"></div>
                <div className="db-resume-name">Candidate Resume</div>
                <div className="db-resume-role">{job_profile.role_title}</div>
              </div>

              <div className="db-resume-section-label">Selected Projects</div>

              {top_matches.slice(0, 3).map((match, idx) => (
                <div key={idx} className="db-resume-project">
                  <div className="db-resume-proj-name">
                    <span>{match.repo_name}</span>
                    <span className="db-resume-proj-source">GitHub</span>
                  </div>
                  {match.resume_bullets?.length > 0 ? (
                    <ul className="db-resume-bullets">
                      {match.resume_bullets.map((b, i) => <li key={i}>{b}</li>)}
                    </ul>
                  ) : (
                    <p style={{fontSize:9,color:'#2a4a2a',marginTop:4,fontStyle:'italic'}}>No bullets generated.</p>
                  )}
                </div>
              ))}

              <div className="db-ats-badge">
                <span className="db-ats-badge-title">ATS Optimized</span>
                <span className="db-ats-badge-sub">Keyword-matched for applicant tracking.</span>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </>
  );
};

export default DashboardView;
